guardMemorySize: 32
bucketMemorySize: 32
cluster:
  address: 'localhost'
  port: 9092
  coordinator:
    address: 'localhost'
    port: 2181
    path: 'databuter'
    baseSleepTimeMs: 1000
    maxRetries: 8