guardMemorySize: 32
bucketMemorySize: 32
client:
  address: 'localhost'
  port: 2423
cluster:
  address: 'localhost'
  port: 9092
  path: 'databuter'
zooKeeper:
  address: 'localhost'
  port: 2181
  baseSleepTimeMs: 1000
  maxRetries: 8