guardMemorySize: 32
bucketMemorySize: 32
expireSchedulePeriod: 60
client:
  endpoint:
    address: 'localhost'
    port: 2423
cluster:
  endpoint:
    address: 'localhost'
    port: 9092
zooKeeper:
  address: 'localhost'
  port: 2181
  path: 'databuter'
  baseSleepTimeMs: 1000
  maxRetries: 8