guardMemorySize: 32
bucketMemorySize: 32
client:
  endpoint:
    address: 'localhost'
    port: 2422
cluster:
  address: 'localhost'
  port: 9091
zooKeeper:
  address: 'localhost'
  port: 2181
  path: 'databuter'
  baseSleepTimeMs: 1000
  maxRetries: 8